import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { CATALOG } from '../src/data/catalog';

// ────────────────────────────────────────────────────────────────────────────
// Emits supabase/seed.sql from the canonical in-code CATALOG, so the database
// seed never drifts from the bundled catalog. Re-run after editing catalog data:
//   npm run seed:sql
// ────────────────────────────────────────────────────────────────────────────

/** Single-quote a SQL string literal, doubling embedded quotes. */
function q(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

const rows = CATALOG.map((p) => {
  const attrs = `${q(JSON.stringify(p.attrs))}::jsonb`;
  const source = p.source ? q(p.source) : 'null';
  return `  (${q(p.id)}, ${q(p.type)}, ${q(p.brand)}, ${q(p.name)}, ${q(p.spec)}, ${attrs}, ${source})`;
});

const sql = `-- Generated by scripts/export-seed.ts — do not edit by hand.
-- Regenerate with: npm run seed:sql
-- ${CATALOG.length} parts. Run AFTER 0001_bikebreaker_init.sql (which creates the table).

insert into bikebreaker.parts (id, type, brand, name, spec, attrs, source) values
${rows.join(',\n')}
on conflict (id) do update set
  type   = excluded.type,
  brand  = excluded.brand,
  name   = excluded.name,
  spec   = excluded.spec,
  attrs  = excluded.attrs,
  source = excluded.source;
`;

const outDir = join(process.cwd(), 'supabase');
mkdirSync(outDir, { recursive: true });
const outFile = join(outDir, 'seed.sql');
writeFileSync(outFile, sql, 'utf8');
console.log(`Wrote ${CATALOG.length} parts → ${outFile}`);
